
SELECT* FROM customer LIMIT 20;

--Q1. What is the total revenue generated by male vs. female customers?
Select gender,SUM (purchase_amount) as revenue
from customer
group by gender

--Q2. Which Customer used a discount but still spent more than the average purchase amount?
Select Customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)from customer)

--Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased,round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 10


--Q4.Compare the average Purchase Amount Between Standard and Express Shipping?

select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5.Total Count of customer that using more which shipping type?

SELECT 
    shipping_type,
    COUNT(DISTINCT customer_id) AS customer_count
FROM customer
GROUP BY shipping_type;

--Q6. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
	ITEM_PURCHASED,
	ROUND(
		100.0 * SUM(
			CASE
				WHEN DISCOUNT_APPLIED = 'Yes' THEN 1
				ELSE 0
			END
		) / COUNT(*),
		2
	) AS DISCOUNT_RATE
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	DISCOUNT_RATE DESC
LIMIT
	5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id,previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 then 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)

SELECT customer_segment,count(*) As " Number of customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

SELECT *
FROM
(SELECT
category,
		item_purchased AS product_name,
		COUNT(*) AS total_purchased,

ROW_NUMBER() OVER(
	PARTITION BY category
	ORDER BY COUNT(*) DESC
) AS rank
FROM customer
GROUP BY category , product_name)

WHERE rank <= 3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
		COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

